#!/bin/sh

usage () {
	if test $# -gt 0
	then
		printf '%s\n' "$*" >&2
	fi
	cat >&2 <<EOF
Usage:
 Write (or overwrite) screen geometries:
	$0 -w [-f]
 Read geometry for the given screen:
	$0 -s <screen|ALL>
 Read geometry for the main (or only) screen:
	$0 -m
 Test whether screen geometry properties have been set:
	$0 -t
EOF
	exit 1
}

eval_read_prop () {
	_prop="$1"
	shift
	_type=16
	_format=""
	_i=0
	for _var in "$@"
	do
		_type="$_type"c
		_format="$_format $_var"'=$'"$_i"
		_i=$(expr $_i + 1)
	done
	_eval="$(xprop -root -notype $_type "$_format"'\n' "$_prop" |\
		sed -n 's/^'"$_prop"' \(.*\)$/\1/p')"
	if test -z "$_eval"
	then
		return 1
	else
		eval "$_eval"
	fi
}

write_prop () {
	_prop="$1"
	shift
	_type=16
	_value="$(printf '%s' "$*" | tr ' ' ',')"
	for _var in "$@"
	do
		_type="$_type"c
	done
	xprop -root -f "$_prop" $_type -set "$_prop" "$_value"
}

read_screen () {
	if ! eval_read_prop SCREEN$1 X Y WIDTH HEIGHT
	then
		usage "Missing X11 properties for screen $1"
	fi
	printf '%d %d %d %d\n' "$X" "$Y" "$WIDTH" "$HEIGHT"
}

TIMID=true
WRITE=true
ISTEST=false
ISMAIN=false
case "$1" in
	-t)
		test $# -eq 1 || usage
		ISTEST=true
		WRITE=false
		;;
	-m)
		test $# -eq 1 || usage
		ISMAIN=true
		WRITE=false
		;;
	-w)
		shift
		if test x"$1" = x-f
		then
			TIMID=false
			shift
		fi
		test $# -eq 0 || usage
		;;
	-s)
		test $# -eq 2 || usage
		if test "$2" != ALL && ! test "$2" -ge 0 2>/dev/null
		then
			usage
		fi
		WRITE=false
		SCREEN=$2
		;;
	*) usage ;;
esac

if eval_read_prop SCREEN_INFO SCREENS MAIN
then
	HASPROPS=true
else
	HASPROPS=false
fi

if $ISTEST
then
	exec $HASPROPS
elif $ISMAIN
then
	if $HASPROPS
	then
		read_screen $MAIN
	else
		xdpyinfo | sed -n \
		's/^ *dimensions:  *\([0-9][0-9]*\)x\([0-9][0-9]*\)  *.*$/0 0 \1 \2/p'
	fi
elif $WRITE
then
	if $TIMID && $HASPROPS
	then
		usage "Not overwriting without the -f flag"
	fi
	eval "$(read MAIN;
	awk -v "MAIN=$MAIN" '
		/^[0-9]+\s+[0-9]+\s+[0-9]+\s+[0-9]+$/ {
			printf("write_prop SCREEN%d %d %d %d %d\n",
				NR-1, $1, $2, $3, $4);
			}
		END { printf("write_prop SCREEN_INFO %d %d\n", NR, MAIN) }
	')"
elif ! $HASPROPS
then
	usage "Missing X11 properties for $(basename "$0"); did you set them?"
else
	if test "$SCREEN" = ALL
	then
		SCREEN=0
		while test $SCREEN -lt $SCREENS
		do
			read_screen $SCREEN
			SCREEN=$(expr $SCREEN + 1)
		done
		exit 0
	fi
	if ! test "$SCREEN" -lt "$SCREENS" -a "$SCREEN" -ge 0 2>/dev/null
	then
		usage "Screen $SCREEN isn't one of the zero-indexed $SCREENS screens"
	fi
	read_screen $SCREEN
fi
