#!/bin/sh

usage () {
	if test $# -gt 0
	then
		printf '%s\n' "$*" >&2
	fi
	cat >&2 <<EOF
Usage:
 Write (or overwrite) properties:
	$0 -w [-f]
 Read properties for the main/given screen:
	$0 [-s <screen|ALL>]
 Test whether properties have been set:
	$0 -t
EOF
	exit 1
}

eval_read_prop () {
	_prop="$1"
	shift
	_type=16
	_format=""
	_i=0
	for _var in "$@"
	do
		_type="$_type"c
		_format="$_format $_var"'=$'"$_i"
		_i=$(expr $_i + 1)
	done
	_eval="$(xprop -root -notype $_type "$_format"'\n' "$_prop" |\
		sed -n 's/^'"$_prop"' \(.*\)$/\1/p')"
	if test -z "$_eval"
	then
		return 1
	else
		eval "$_eval"
	fi
}

write_prop () {
	_prop="$1"
	shift
	_type=16
	_value="$(printf '%s' "$*" | tr ' ' ',')"
	for _var in "$@"
	do
		_type="$_type"c
	done
	xprop -root -f "$_prop" $_type -set "$_prop" "$_value"
}

read_screen () {
	if ! eval_read_prop SCREEN$1 X Y WIDTH HEIGHT
	then
		usage "Missing X11 properties for screen $1"
	fi
	printf '%d %d %d %d\n' "$X" "$Y" "$WIDTH" "$HEIGHT"
}

TIMID=true
WRITE=true
ISTEST=false
case $# in
	0) WRITE=false ;;
	1)
		if test x"$1" = x-t
		then
			ISTEST=true
		elif test x"$1" != x-w
		then
			usage
		fi
		;;
	2)
		if test x"$1" = x-w -a x"$2" = x-f
		then
			TIMID=false
		elif test x"$1" = x-s
		then
			if test "$2" != ALL && test "$2" -lt 0
			then
				usage
			fi
			WRITE=false
			SCREEN=$2
		else
			usage
		fi
		;;
	*) usage
esac

if eval_read_prop SCREEN_INFO SCREENS MAIN
then
	HASPROPS=true
else
	HASPROPS=false
fi

if $ISTEST
then
	exec $HASPROPS
elif $WRITE
then
	if $TIMID && $HASPROPS
	then
		usage "Not overwriting without the -f flag"
	fi
	eval "$(read MAIN;
	awk -v "MAIN=$MAIN" '
		/^[0-9]+\s+[0-9]+\s+[0-9]+\s+[0-9]+$/ {
			printf("write_prop SCREEN%d %d %d %d %d\n",
				NR-1, $1, $2, $3, $4);
			}
		END { printf("write_prop SCREEN_INFO %d %d\n", NR, MAIN) }
	')"
elif ! $HASPROPS
then
	usage "Missing X11 properties for $(basename "$0"); did you set them?"
else
	if test -z "$SCREEN"
	then
		SCREEN=$MAIN
	fi
	if test "$SCREEN" = ALL
	then
		SCREEN=0
		while test $SCREEN -lt $SCREENS
		do
			read_screen $SCREEN
			SCREEN=$(expr $SCREEN + 1)
		done
		exit 0
	fi
	if ! test "$SCREEN" -lt "$SCREENS" -a "$SCREEN" -ge 0 2>/dev/null
	then
		usage "Screen $SCREEN isn't one of the zero-indexed $SCREENS screens"
	fi
	read_screen $SCREEN
fi
