#!/bin/sh

verfile="$(
	find . -maxdepth 2 \
		-name \*.csproj -o \
		-name Directory.Build.props |\
	grep '^\./\(app/\|library/\|src/\|\)[^/]\+$' |\
	xargs grep -l '</AssemblyVersion>' |\
	head -1
	)"
if test -z "$verfile"
then
	echo "Could not find a build props file" >&2
	exit 1
fi
xmlstarlet sel -t --value-of /Project/PropertyGroup/AssemblyVersion $verfile |\
	sed -n 's/^\([0-9]\.[0-9]\+\.[0-9]\+\).*$/\1/p'

