#!/bin/sh

usage () {
	echo "Usage: $0 [-acdlrw] <storage account> <blob container> [timespan]" >&2
	echo "Timespan examples: 20m, 2h, 31d; default: 1d"
	exit 1
}

PERMARGS="--permissions r"
case "x$1" in
	x-[acdlrw]*)
		PERMARGS="--permissions $(echo x$1 | cut -c3-)"
		shift
		;;
esac

test $# -gt 3 -o -z "$1" -o -z "$2" && usage

TMPF=`mktemp`
trap "rm -f $TMPF" EXIT

TIMESPAN=${3:-"1d"}
echo "$TIMESPAN" | tr -d 'mhd\012' > $TMPF

case "${#TIMESPAN}-$TIMESPAN" in
	[234]-[0-9]*m)
		echo ' * 60' | tr -d '\012' >> $TMPF
		;;
	[234]-[0-9]*h)
		echo ' * 60 * 60' | tr -d '\012' >> $TMPF
		;;
	[234]-[0-9]*d)
		echo ' * 24 * 60 * 60' | tr -d '\012' >> $TMPF
		;;
	*)
		echo "Invalid timespan: '$TIMESPAN'" >&2
		usage
		;;
esac

echo " + $(date +%s)" >> $TMPF
EXPIRY=$(date -u -d @$(bc < $TMPF) +%FT%TZ)

if ! az storage container generate-sas \
	$PERMARGS \
	--account-name $1 -n $2 --expiry $EXPIRY -o tsv \
	2>$TMPF | sed 's/^./?&/'
then
	cat $TMPF >&2
	exit 1
fi
