#!/bin/sh

usage () {
	echo "Usage: $0 <vault name> [regex]" >&2
	exit 1
}

if test $# -lt 1 -o $# -gt 2 -o "$(echo x"$1" | cut -c1-2)" = x-
then
	usage
fi

VAULT="$1"
shift
ALLSECRETS=$(mktemp)
trap "rm -f $ALLSECRETS" EXIT

az keyvault secret list \
	--vault-name "$VAULT" \
	-o tsv --query '[].{ name: name }' > $ALLSECRETS

if test $(wc -l < $ALLSECRETS) -eq 0
then
	echo 'No secrets found. Are you logged in?' >&2
	exit 1
fi

if test $# -eq 1
then
	set -- -f "$1"
fi
secret="$(list-select $ALLSECRETS -f "$@")"

if test $? -eq 0 -a -n "$secret"
then
	exec az keyvault secret show \
		--vault-name "$VAULT" \
		--name "$secret" \
		--query value -o tsv
fi
