#!/bin/sh

usage () {
	echo "Usage: $0 <vault name> [regex]" >&2
	exit 1
}

listoptions () {
	 awk -F '	' '
	 { printf("%2d. %s\n", NR, $0) }
	 ' $FILTEREDSECRETS
}

showsecret () {
	exec az keyvault secret show \
		--vault-name "$VAULT" \
		--name $(sed -n "$1"p $FILTEREDSECRETS) \
		--query value -o tsv
}

if test $# -gt 2 -o "$(echo x"$1" | cut -c1-2)" = x-
then
	usage
fi

VAULT="$1"
shift
ALLSECRETS=$(mktemp)
FILTEREDSECRETS=$(mktemp)
trap "rm -f $ALLSECRETS $FILTEREDSECRETS" EXIT

az keyvault secret list \
	--vault-name "$VAULT" \
	-o tsv --query '[].{ name: name }' > $ALLSECRETS

if test $(wc -l < $ALLSECRETS) -eq 0
then
	echo 'No secrets found. Are you logged in?' >&2
	exit 1
fi

if test $# -eq 1
then
	grep "$1" $ALLSECRETS > $FILTEREDSECRETS
else
	cp $ALLSECRETS $FILTEREDSECRETS
fi

case $(wc -l < $FILTEREDSECRETS) in
	0) echo "No matching secrets" >&2; exit 1 ;;
	1) showsecret 1 ;;
	*) listoptions ;;
esac

while true
do
	printf '\nSelect: '
	read choice
	case "$choice" in
		q) exit ;;
		''|*[!0-9]*) listoptions ;;
		*)
			if test $choice -gt 0 -a \
				$choice -le $(wc -l < $FILTEREDSECRETS)
			then
				showsecret $choice
			fi
	esac
done

