#!/bin/sh

usage () {
	echo "Usage: $0 <resource group> <app service> <package>" >&2
	exit 1
}

RESOURCEGROUP="$1"
APPSERVICE="$2"
PACKAGEFILE="$3"

if test $# -ne 3 -o ! -r "$3"
then
	usage
fi

exec az functionapp deployment source config-zip \
	--resource-group "$RESOURCEGROUP" \
	--name "$APPSERVICE" \
	--src "$PACKAGEFILE"
