#!/bin/sh

usage () {
	echo "Usage: $0 <vault name> <name> <value|-f file>" >&2
	exit 1
}

showsecret () {
	exec az keyvault secret show \
		--vault-name "$VAULT" \
		--name $(sed -n "$1"p $FILTEREDSECRETS) \
		--query value -o tsv
}

if test $# -lt 3 -o \
	$# -gt 4 -o \
	\( $# -eq 4 -a \( x"$3" != "x-f" -o ! -r "$4" \) \)
then
	usage
fi

VAULT="$1"
SECRETNAME="$2"
if test $# -eq 3
then
	SECRETVALUE=$(mktemp)
	trap "rm -f $SECRETVALUE" EXIT
	printf %s "$3" > $SECRETVALUE
else
	SECRETVALUE="$4"
fi

az keyvault secret set \
	--vault-name "$VAULT" \
	--name "$SECRETNAME" \
	--file "$SECRETVALUE"

