#!/bin/sh

usage () {
	echo "Usage: $0 [-|file.plist]" >&2
	exit 1
}

case $# in
	0) ;;
	1)
		if test x"$1" != "x-"
		then
			if test -r "$1"
			then
				exec < "$1"
			else
				usage
			fi
		fi
		;;
	*) usage ;;
esac

exec plutil -convert json -o - -
