#!/bin/sh

args="-listen unix -nolisten inet6"
wsl="/cygdrive/c/Windows/system32/wsl"
if test -x "$wsl" && test $("$wsl" --list --running -v | wc -l) -gt 1
then
	args="$args -listen tcp"
else
	args="$args -nolisten tcp"
fi

exec /bin/run /bin/Xwin "$@" $args
