
Host gitlabu1
Tunnel no
ForwardAgent no
ForwardX11 no
HostName gitlab.com
user git
IdentityFile ~/.ssh/githubu1.pub

Host gitlabu2
Tunnel no
ForwardAgent no
ForwardX11 no
HostName gitlab.com
user git
IdentityFile ~/.ssh/githubu2.pub

Host gitlabu3
Tunnel no
ForwardAgent no
ForwardX11 no
HostName gitlab.com
user git
IdentityFile ~/.ssh/githubu3.pub

Host gitlabpro
Tunnel no
ForwardAgent no
ForwardX11 no
HostName gitlab.com
user git
IdentityFile ~/.ssh/githubpro.pub

