
function zshsulogin () {
	echo sudo login -f root env "$@" zsh -l
}

alias strace=dtruss
alias sudoedit='sudo -e'

function p () {
	qlmanage -p "$@" >/dev/null 2>&1 &
}

function tmexclusions () {
	local _sudo=$(test x"$1" = "x-a" && echo "sudo")
	$_sudo mdfind "com_apple_backup_excludeItem = 'com.apple.backupd'"
}
